### ISSUE TITLE
need supprt for 1024X768 monitors

### ISSUE THREAD

**Issue by ID453543435** [syscoin/syscoin2#61] opened 2016-05-02 00:18 UTC
need supprt for 1024X768 monitors

**Comment by sidhujag** [comment] 2016-05-02 00:25
yes not preferred to use that.. you have to double click on the window title twice to resize the application to your resolution... try that.

**Comment by dwasyluk** [comment] 2016-05-04 19:42
Duplicate of #32

**Closed by dwasyluk** 2016-05-04 19:42 UTC
