### ISSUE TITLE
pauxpow exception

### ISSUE THREAD

**Issue by sidhujag** [syscoin/syscoin2#130] opened 2017-01-05 22:20 UTC
Running at qt, at random times we'd see the dreaded pauxpow runtime error and crash

**Comment by sebastien1234** [comment] 2017-01-15 21:22
nothing from me so-far, @mca confirmed he's not getting the error, keeping open for further testing

**Comment by dwasyluk** [comment] 2017-02-07 20:34
I've also not been able reproduce on the latest 2.1.2 test candidate and I know Keyare has been unable to reproduce as well. Given the confirmation from multiple sources I'm closing.

**Closed by dwasyluk** 2017-02-07 20:34 UTC
Labels: bug, test fix
