### ISSUE TITLE
Messages are not going into outbox

### ISSUE THREAD

**Issue by mucalov** [syscoin/syscoin2#4] opened 2016-02-29 17:59 UTC
When you send a message, it doesn't end up in Outbox. It is received in Inbox, but there is no trace in Outbox.

**Comment by sidhujag** [comment] 2016-03-01 03:51
seems to work, did you wait for one confirm? Im thinking i may have them show up right away just not usable until a confrim, might be a better design

**Comment by mucalov** [comment] 2016-03-02 00:53
Nope, they never showed in outbox, whole day has passed. I tested again from scratch (with new wallet), same problem again.

**Comment by sidhujag** [comment] 2016-03-02 01:55
Can you get latest syscoin.conf file from the blog and run wallet create message which doesnt show (even after confirm and refresh button) and attach the debug.log file?

**Comment by sidhujag** [comment] 2016-03-05 00:09
retest in latest version

**Comment by sebastien1234** [comment] 2016-03-11 04:44
Yeah for this one, I cannot reproduce an error, seems fine @sidhujag, at least in the 3/7/2016 build

**Comment by Keyare** [comment] 2016-03-20 22:16
I get this error only when sending a message to an Alias in the same wallet.

**Comment by sebastien1234** [comment] 2016-03-21 02:59
I can also confir @sidhujag that this only happens when I send myself a message to an alias I own on 3/17 build

**Comment by sebastien1234** [comment] 2016-06-25 16:28
@sidhujag issue #4 remains as we are still able to send messages to aliases we own, even in Syscoin 2.1 alpha. Should not be able to send yourself messages in the same wallet and since you can still do that, the message only appears in INBOX and not in OUTBOX.

**Comment by willyko** [comment] 2018-02-27 18:59
Closing this issue since message feature has been moved to Blockmarket

**Closed by willyko** 2018-02-27 18:59 UTC
Labels: bug, test fix
